### PR TITLE
Catalog Capstone Project

### PR DESCRIPTION
**Pull request by taldr27**
## In this capstone project we @Gleennkar @taldr27:
- Created a kanban board and divided all the tasks into cards to correctly divide all the work between members.
- Followed the provided UML diagram to create different classes and methods.
- Created all the requested associations in classes.
- Created all the requested methods in all the classes
- Implemented encapsulation and inheritance with Ruby
- Created a `main.rb` file that serves as your console app entry point.
- Created a UI to show all the available options for the user:
    - List all books
    - List all music albums
    - List all movies
    - List of games
    - List all genres (e.g 'Comedy', 'Thriller')
    - List all labels (e.g. 'Gift', 'New')
    - List all authors (e.g. 'Stephen King')
    - List all sources (e.g. 'From a friend', 'Online shop')
    - Add a book
    - Add a music album
    - Add a movie
    - Add a game
- Stored data in json files
- Created a `schema.sql` file that contains all the tables of our database.
- Worked as a team assigning specific roles to all of our members.
gif
We had a third partner but he left our group because they allowed him to continue next week!

https://user-images.githucontent.com/10724/2132995-64fd-46ee-b892-95550d025df6.mp4

### CODE REVIEW

**Review by sumairq — CHANGES_REQUESTED** [review]
## Hi Team, 



Good job so far!
There is only one thing left that you still need to work on to finalize your project but you are almost there!

## Highlights: 
✔️ Good commit history
✔️Linters are passing
✔️Professional README
✔️Correct Git flow
✔️Descriptive PR

## Suggested changes
- [ ] You have made an awesome project. Let's try to keep the presentation video's length under 5 minutes to meet the requirements. Cheers 👍 

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by taldr27** [comment]
@sumairq Thanks for your review, We just updated our video to meet the requirements.

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Linter is green (the last commit has a green check mark (✅)) 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used  👏

 ## Required Changes ♻️
- **Please, make available the link to the updated video as requested by my previous colleague.**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mirouhml — APPROVED** [review]
# APPROVED 🟢

Hi Team, 

Thanks for adding the video, your project is now complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by taldr27** [comment]
@mirouhml thank you very much for your review! 🙏🙏

**Pull request merged**
